#pragma once

// Engine custom keycodes
// original keycodes adquired from GLFW3

// The unknown key
#define COOKIE_KEY_UNKNOWN -1

// Printable keys
#define COOKIE_KEY_SPACE 32
#define COOKIE_KEY_APOSTROPHE 39 /* ' */
#define COOKIE_KEY_COMMA 44		 /* , */
#define COOKIE_KEY_MINUS 45		 /* - */
#define COOKIE_KEY_PERIOD 46	 /* . */
#define COOKIE_KEY_SLASH 47		 /* / */
#define COOKIE_KEY_0 48
#define COOKIE_KEY_1 49
#define COOKIE_KEY_2 50
#define COOKIE_KEY_3 51
#define COOKIE_KEY_4 52
#define COOKIE_KEY_5 53
#define COOKIE_KEY_6 54
#define COOKIE_KEY_7 55
#define COOKIE_KEY_8 56
#define COOKIE_KEY_9 57
#define COOKIE_KEY_SEMICOLON 59 /* ; */
#define COOKIE_KEY_EQUAL 61		/* = */
#define COOKIE_KEY_A 65
#define COOKIE_KEY_B 66
#define COOKIE_KEY_C 67
#define COOKIE_KEY_D 68
#define COOKIE_KEY_E 69
#define COOKIE_KEY_F 70
#define COOKIE_KEY_G 71
#define COOKIE_KEY_H 72
#define COOKIE_KEY_I 73
#define COOKIE_KEY_J 74
#define COOKIE_KEY_K 75
#define COOKIE_KEY_L 76
#define COOKIE_KEY_M 77
#define COOKIE_KEY_N 78
#define COOKIE_KEY_O 79
#define COOKIE_KEY_P 80
#define COOKIE_KEY_Q 81
#define COOKIE_KEY_R 82
#define COOKIE_KEY_S 83
#define COOKIE_KEY_T 84
#define COOKIE_KEY_U 85
#define COOKIE_KEY_V 86
#define COOKIE_KEY_W 87
#define COOKIE_KEY_X 88
#define COOKIE_KEY_Y 89
#define COOKIE_KEY_Z 90
#define COOKIE_KEY_LEFT_BRACKET 91	/* [ */
#define COOKIE_KEY_BACKSLASH 92		/* \ */
#define COOKIE_KEY_RIGHT_BRACKET 93 /* ] */
#define COOKIE_KEY_GRAVE_ACCENT 96	/* ` */
#define COOKIE_KEY_WORLD_1 161		/* non-US #1 */
#define COOKIE_KEY_WORLD_2 162		/* non-US #2 */

/* Function keys */
#define COOKIE_KEY_ESCAPE 256
#define COOKIE_KEY_ENTER 257
#define COOKIE_KEY_TAB 258
#define COOKIE_KEY_BACKSPACE 259
#define COOKIE_KEY_INSERT 260
#define COOKIE_KEY_DELETE 261
#define COOKIE_KEY_RIGHT 262
#define COOKIE_KEY_LEFT 263
#define COOKIE_KEY_DOWN 264
#define COOKIE_KEY_UP 265
#define COOKIE_KEY_PAGE_UP 266
#define COOKIE_KEY_PAGE_DOWN 267
#define COOKIE_KEY_HOME 268
#define COOKIE_KEY_END 269
#define COOKIE_KEY_CAPS_LOCK 280
#define COOKIE_KEY_SCROLL_LOCK 281
#define COOKIE_KEY_NUM_LOCK 282
#define COOKIE_KEY_PRINT_SCREEN 283
#define COOKIE_KEY_PAUSE 284
#define COOKIE_KEY_F1 290
#define COOKIE_KEY_F2 291
#define COOKIE_KEY_F3 292
#define COOKIE_KEY_F4 293
#define COOKIE_KEY_F5 294
#define COOKIE_KEY_F6 295
#define COOKIE_KEY_F7 296
#define COOKIE_KEY_F8 297
#define COOKIE_KEY_F9 298
#define COOKIE_KEY_F10 299
#define COOKIE_KEY_F11 300
#define COOKIE_KEY_F12 301
#define COOKIE_KEY_F13 302
#define COOKIE_KEY_F14 303
#define COOKIE_KEY_F15 304
#define COOKIE_KEY_F16 305
#define COOKIE_KEY_F17 306
#define COOKIE_KEY_F18 307
#define COOKIE_KEY_F19 308
#define COOKIE_KEY_F20 309
#define COOKIE_KEY_F21 310
#define COOKIE_KEY_F22 311
#define COOKIE_KEY_F23 312
#define COOKIE_KEY_F24 313
#define COOKIE_KEY_F25 314
#define COOKIE_KEY_KP_0 320
#define COOKIE_KEY_KP_1 321
#define COOKIE_KEY_KP_2 322
#define COOKIE_KEY_KP_3 323
#define COOKIE_KEY_KP_4 324
#define COOKIE_KEY_KP_5 325
#define COOKIE_KEY_KP_6 326
#define COOKIE_KEY_KP_7 327
#define COOKIE_KEY_KP_8 328
#define COOKIE_KEY_KP_9 329
#define COOKIE_KEY_KP_DECIMAL 330
#define COOKIE_KEY_KP_DIVIDE 331
#define COOKIE_KEY_KP_MULTIPLY 332
#define COOKIE_KEY_KP_SUBTRACT 333
#define COOKIE_KEY_KP_ADD 334
#define COOKIE_KEY_KP_ENTER 335
#define COOKIE_KEY_KP_EQUAL 336
#define COOKIE_KEY_LEFT_SHIFT 340
#define COOKIE_KEY_LEFT_CONTROL 341
#define COOKIE_KEY_LEFT_ALT 342
#define COOKIE_KEY_LEFT_SUPER 343
#define COOKIE_KEY_RIGHT_SHIFT 344
#define COOKIE_KEY_RIGHT_CONTROL 345
#define COOKIE_KEY_RIGHT_ALT 346
#define COOKIE_KEY_RIGHT_SUPER 347
#define COOKIE_KEY_MENU 348

// Mouse keycodes
#define COOKIE_MOUSE_BUTTON_1 0
#define COOKIE_MOUSE_BUTTON_2 1
#define COOKIE_MOUSE_BUTTON_3 2
#define COOKIE_MOUSE_BUTTON_4 3
#define COOKIE_MOUSE_BUTTON_5 4
#define COOKIE_MOUSE_BUTTON_6 5
#define COOKIE_MOUSE_BUTTON_7 6
#define COOKIE_MOUSE_BUTTON_8 7
#define COOKIE_MOUSE_BUTTON_LAST COOKIE_MOUSE_BUTTON_8
#define COOKIE_MOUSE_BUTTON_LEFT COOKIE_MOUSE_BUTTON_1
#define COOKIE_MOUSE_BUTTON_RIGHT COOKIE_MOUSE_BUTTON_2
#define COOKIE_MOUSE_BUTTON_MIDDLE COOKIE_MOUSE_BUTTON_3